# Generated by Django 6.0.3 on 2026-06-22 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer', models.CharField(max_length=80)),
                ('gist_url', models.URLField()),
                ('gist_id', models.CharField(editable=False, max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['customer', 'gist_id'],
                'constraints': [models.UniqueConstraint(fields=('customer', 'gist_id'), name='unique_report_customer_gist')],
            },
        ),
    ]
