# Generated by Django 6.0.3 on 2026-06-22 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='customer_name',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='report',
            name='end_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='report',
            name='start_date',
            field=models.DateField(null=True),
        ),
    ]
