# Generated by Django 6.0.3 on 2026-06-25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portal", "0002_report_customer_name_report_end_date_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="report",
            name="report_type",
            field=models.CharField(
                choices=[("weekly", "Weekly"), ("engineering", "Engineering")], default="weekly", max_length=24
            ),
        ),
        migrations.AddField(
            model_name="report",
            name="title",
            field=models.CharField(blank=True, max_length=180),
        ),
        migrations.AlterField(
            model_name="report",
            name="end_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="report",
            name="start_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
