# Generated by Django 6.0.3 on 2026-07-14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portal", "0003_report_report_type_report_title"),
    ]

    operations = [
        migrations.CreateModel(
            name="Release",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("topic", models.SlugField(max_length=80)),
                ("release_date", models.DateField()),
                ("gist_url", models.URLField()),
                ("gist_id", models.CharField(editable=False, max_length=64)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["topic", "-release_date"],
                "constraints": [
                    models.UniqueConstraint(fields=("topic", "release_date"), name="unique_release_topic_date")
                ],
            },
        ),
    ]
