# Generated by Django 6.0.3 on 2026-07-14 22:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0004_release'),
    ]

    operations = [
        migrations.AlterField(
            model_name='release',
            name='topic',
            field=models.CharField(max_length=80, validators=[django.core.validators.RegexValidator(message='Topics can contain letters, numbers, spaces, hyphens, and underscores.', regex='^[-a-zA-Z0-9_ ]+$')]),
        ),
    ]
