# Generated by Django 6.0.3 on 2026-07-16 04:55

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CatalogOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.SlugField(max_length=80, unique=True)),
                ('category', models.CharField(choices=[('service', 'Service'), ('pc', 'PC'), ('panel', 'Panel'), ('license', 'Ignition license'), ('subscription', 'Subscription')], max_length=20)),
                ('name', models.CharField(max_length=160)),
                ('description', models.TextField(blank=True)),
                ('cost_cents', models.PositiveIntegerField(blank=True, null=True)),
                ('amount_cents', models.PositiveIntegerField(blank=True, null=True)),
                ('markup_percent', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=5)),
                ('cadence', models.CharField(choices=[('once', 'One time'), ('annual', 'Annual'), ('custom', 'Custom quote')], default='once', max_length=12)),
                ('external_url', models.URLField(blank=True)),
                ('specifications', models.JSONField(blank=True, default=dict)),
                ('price_checked_at', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['category', 'sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='UpdateRelease',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=160)),
                ('version', models.CharField(max_length=80)),
                ('severity', models.CharField(default='routine', max_length=20)),
                ('release_notes', models.TextField()),
                ('compatibility', models.JSONField(default=dict)),
                ('artifact_url', models.URLField(blank=True)),
                ('artifact_sha256', models.CharField(blank=True, max_length=64)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=160)),
                ('status', models.CharField(choices=[('pending', 'Pending enrollment'), ('active', 'Active'), ('spare', 'Spare'), ('lost', 'Lost'), ('retired', 'Retired')], default='pending', max_length=16)),
                ('last_seen_at', models.DateTimeField(blank=True, null=True)),
                ('agent_version', models.CharField(blank=True, max_length=40)),
                ('inventory', models.JSONField(blank=True, default=dict)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devices', to='organizations.organization')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AuditEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=120)),
                ('object_type', models.CharField(max_length=80)),
                ('object_id', models.CharField(max_length=80)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_events', to='organizations.organization')),
                ('actor_device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='panellock.device')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DeviceCredential',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_key', models.TextField()),
                ('fingerprint', models.CharField(max_length=64, unique=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('rotated_at', models.DateTimeField(blank=True, null=True)),
                ('device', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='credential', to='panellock.device')),
            ],
        ),
        migrations.CreateModel(
            name='EstimateRequest',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('project_type', models.CharField(choices=[('conversion', 'Convert an HMI to Ignition'), ('upgrade', 'Upgrade an existing Ignition panel'), ('gateway', 'Gateway or multi-panel project (custom)')], max_length=16)),
                ('source_platform', models.CharField(max_length=100)),
                ('source_version', models.CharField(blank=True, max_length=80)),
                ('panel_quantity', models.PositiveSmallIntegerField(default=1)),
                ('screen_count', models.PositiveIntegerField(default=0)),
                ('tag_count', models.PositiveIntegerField(default=0)),
                ('driver_count', models.PositiveIntegerField(default=0)),
                ('backup_available', models.BooleanField(default=False)),
                ('requested_timeline', models.CharField(blank=True, max_length=120)),
                ('notes', models.TextField(blank=True)),
                ('contact_name', models.CharField(max_length=120)),
                ('company', models.CharField(max_length=160)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=40)),
                ('follow_up_requested', models.BooleanField(default=False)),
                ('one_time_total_cents', models.PositiveIntegerField(default=0)),
                ('annual_total_cents', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('submitted', 'Submitted'), ('reviewing', 'Reviewing'), ('quoted', 'Quoted'), ('closed', 'Closed')], default='submitted', max_length=16)),
                ('terms_accepted_at', models.DateTimeField()),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='estimates', to='organizations.organization')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EstimateLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=80)),
                ('description', models.CharField(max_length=220)),
                ('quantity', models.PositiveSmallIntegerField()),
                ('unit_amount_cents', models.PositiveIntegerField()),
                ('cadence', models.CharField(choices=[('once', 'One time'), ('annual', 'Annual'), ('custom', 'Custom quote')], max_length=12)),
                ('source_cost_cents', models.PositiveIntegerField(blank=True, null=True)),
                ('external_url', models.URLField(blank=True)),
                ('price_checked_at', models.DateField(blank=True, null=True)),
                ('offer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='panellock.catalogoffer')),
                ('estimate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='panellock.estimaterequest')),
            ],
        ),
        migrations.CreateModel(
            name='FollowUpRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('preferred_contact', models.CharField(choices=[('email', 'Email'), ('phone', 'Phone'), ('meeting', 'Meeting')], max_length=20)),
                ('best_time', models.CharField(blank=True, max_length=120)),
                ('details', models.TextField(blank=True)),
                ('estimate', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='follow_up', to='panellock.estimaterequest')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Panel',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=160)),
                ('asset_tag', models.CharField(blank=True, max_length=80)),
                ('ignition_version', models.CharField(blank=True, max_length=40)),
                ('criticality', models.CharField(default='standard', max_length=20)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='panels', to='organizations.organization')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EnrollmentToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token_hash', models.CharField(editable=False, max_length=64, unique=True)),
                ('intended_name', models.CharField(max_length=160)),
                ('as_spare', models.BooleanField(default=False)),
                ('expires_at', models.DateTimeField()),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollment_tokens', to='organizations.organization')),
                ('panel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='enrollment_tokens', to='panellock.panel')),
            ],
        ),
        migrations.CreateModel(
            name='BackupAsset',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('original_filename', models.CharField(max_length=255)),
                ('object_key', models.CharField(max_length=500, unique=True)),
                ('size_bytes', models.PositiveBigIntegerField()),
                ('sha256', models.CharField(blank=True, max_length=64)),
                ('scan_status', models.CharField(choices=[('pending', 'Pending'), ('clean', 'Clean'), ('quarantined', 'Quarantined'), ('rejected', 'Rejected')], default='pending', max_length=16)),
                ('retention_until', models.DateField()),
                ('pre_update', models.BooleanField(default=False)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='backups', to='organizations.organization')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('panel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='backups', to='panellock.panel')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=160)),
                ('source_platform', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(default='active', max_length=20)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='panellock_projects', to='organizations.organization')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='panel',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='panels', to='panellock.project'),
        ),
        migrations.CreateModel(
            name='ProvisioningPlan',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('version', models.PositiveIntegerField(default=1)),
                ('request_text', models.TextField(blank=True)),
                ('operations', models.JSONField(default=list)),
                ('operations_sha256', models.CharField(max_length=64)),
                ('status', models.CharField(default='draft', max_length=20)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='plans', to='panellock.device')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='provisioning_plans', to='organizations.organization')),
            ],
        ),
        migrations.CreateModel(
            name='PlanApproval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operations_sha256', models.CharField(max_length=64)),
                ('approved_at', models.DateTimeField(auto_now_add=True)),
                ('approved_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approvals', to='panellock.provisioningplan')),
            ],
        ),
        migrations.CreateModel(
            name='Site',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=160)),
                ('address', models.TextField(blank=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sites', to='organizations.organization')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='project',
            name='site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to='panellock.site'),
        ),
        migrations.AddField(
            model_name='panel',
            name='site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='panels', to='panellock.site'),
        ),
        migrations.CreateModel(
            name='UpdateJob',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(default='queued', max_length=20)),
                ('claimed_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='jobs', to='panellock.device')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='update_jobs', to='organizations.organization')),
                ('plan', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='job', to='panellock.provisioningplan')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UpdateRequest',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('requested', 'Requested'), ('needs_info', 'Needs information'), ('approved', 'Approved'), ('scheduled', 'Scheduled'), ('precheck', 'Precheck'), ('in_progress', 'In progress'), ('verifying', 'Verifying'), ('completed', 'Completed'), ('failed', 'Failed'), ('rolled_back', 'Rolled back'), ('canceled', 'Canceled')], default='requested', max_length=20)),
                ('maintenance_window', models.DateTimeField(blank=True, null=True)),
                ('downtime_acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('backup', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='panellock.backupasset')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='update_requests', to='organizations.organization')),
                ('panel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='update_requests', to='panellock.panel')),
                ('release', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='update_requests', to='panellock.updaterelease')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='requested_updates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='provisioningplan',
            name='update_request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plans', to='panellock.updaterequest'),
        ),
        migrations.CreateModel(
            name='DeviceNonce',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nonce', models.CharField(max_length=80)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('credential', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nonces', to='panellock.devicecredential')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('credential', 'nonce'), name='unique_device_nonce')],
            },
        ),
        migrations.CreateModel(
            name='ManagedCoverage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('starts_at', models.DateTimeField()),
                ('ends_at', models.DateTimeField(blank=True, null=True)),
                ('stripe_subscription_id', models.CharField(blank=True, max_length=120)),
                ('status', models.CharField(default='active', max_length=20)),
                ('panel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coverage_records', to='panellock.panel')),
            ],
            options={
                'constraints': [models.UniqueConstraint(condition=models.Q(('status', 'active')), fields=('panel',), name='one_active_coverage_per_panel')],
            },
        ),
        migrations.CreateModel(
            name='DeviceAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='panellock.device')),
                ('panel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='device_assignments', to='panellock.panel')),
            ],
            options={
                'constraints': [models.UniqueConstraint(condition=models.Q(('ended_at__isnull', True)), fields=('device',), name='one_active_panel_per_device'), models.UniqueConstraint(condition=models.Q(('ended_at__isnull', True)), fields=('panel',), name='one_active_device_per_panel')],
            },
        ),
        migrations.CreateModel(
            name='UpdateEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence', models.PositiveIntegerField()),
                ('event_type', models.CharField(max_length=80)),
                ('payload', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='panellock.updatejob')),
            ],
            options={
                'ordering': ['sequence'],
                'constraints': [models.UniqueConstraint(fields=('job', 'sequence'), name='unique_job_event_sequence')],
            },
        ),
        migrations.CreateModel(
            name='UpdateNotice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='update_notices', to='organizations.organization')),
                ('panel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='update_notices', to='panellock.panel')),
                ('release', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notices', to='panellock.updaterelease')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('panel', 'release'), name='unique_panel_release_notice')],
            },
        ),
        migrations.AddConstraint(
            model_name='provisioningplan',
            constraint=models.UniqueConstraint(fields=('update_request', 'version'), name='unique_update_plan_version'),
        ),
    ]
