# Generated by Django 6.0.3 on 2026-07-16 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panellock', '0002_seed_catalog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='updaterelease',
            name='compatibility',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
