# Generated by Django 6.0.3 on 2026-07-16 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panellock', '0003_alter_updaterelease_compatibility'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending enrollment'), ('active', 'Active'), ('spare', 'Spare'), ('reserved', 'Reserved for replacement'), ('lost', 'Lost'), ('retired', 'Retired')], default='pending', max_length=16),
        ),
    ]
