# Generated by Django 6.0.3 on 2026-07-16 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0001_initial'),
        ('panellock', '0004_alter_device_status'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='updatejob',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['queued', 'claimed', 'in_progress'])), fields=('device',), name='one_active_update_job_per_device'),
        ),
    ]
