# Generated by Django 6.0.3 on 2026-07-16 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panellock', '0005_updatejob_one_active_update_job_per_device'),
    ]

    operations = [
        migrations.AlterField(
            model_name='updateevent',
            name='payload',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
